### ISSUE TITLE
Short, Simple way but how to login?

### ISSUE THREAD

**Issue by manishlok** [s-damian/damian-php#1]
This is seriously short and simple framework. I am developing a CMS-like project. Could you guide me how to login as admin ?
Do I have to make form request and where to put authentication code?

**Comment by s-damian** [comment]
Hello.
I put an example login controller: [Auth Controllers](https://github.com/s-damian/damian-php/tree/main/app/Http/Controllers/Admin/Auth)
Thanks for your message.

**Comment by manishlok** [comment]
I appreciate your fast response. Wish to see this project goes far. Thanks
